// Generated by CoffeeScript 1.6.2
var Q, fs, getReporter, glob, globPath, globPaths, loadFile, loadHelpers, loadMatchers, loadSpecs, loadSpectacular, m, path, requireIntoGlobal, util, vm, walk;

m = require('module');

fs = require('fs');

glob = require('glob');

path = require('path');

vm = require('vm');

Q = require('q');

walk = require('walkdir');

util = require('util');

requireIntoGlobal = function(file) {
  var k, matchers, v, _results;

  matchers = require(file);
  _results = [];
  for (k in matchers) {
    v = matchers[k];
    if (typeof v === 'function') {
      v._name = k;
    }
    _results.push(global[k] = v);
  }
  return _results;
};

loadSpectacular = function(options) {
  return Q.fcall(function() {
    var filename, src;

    filename = path.resolve(__dirname, "spectacular.js");
    src = fs.readFileSync(filename).toString();
    vm.runInThisContext(src, filename);
    spectacular.env = new spectacular.Environment(options);
    return spectacular.env.globalize();
  });
};

loadMatchers = function(options) {
  var defer, emitter;

  defer = Q.defer();
  if (options.noMatchers) {
    defer.resolve();
  } else {
    emitter = walk(options.matchersRoot);
    emitter.on('file', function(path, stat) {
      return requireIntoGlobal(path);
    });
    emitter.on('end', function() {
      return defer.resolve();
    });
  }
  return defer.promise;
};

loadHelpers = function(options) {
  var defer, emitter;

  defer = Q.defer();
  if (options.noHelpers) {
    defer.resolve();
  } else {
    emitter = walk(options.helpersRoot);
    emitter.on('file', function(path, stat) {
      return requireIntoGlobal(path);
    });
    emitter.on('end', function() {
      return defer.resolve();
    });
  }
  return defer.promise;
};

globPath = function(path) {
  var defer;

  defer = Q.defer();
  glob(path, function(err, res) {
    if (err) {
      return defer.reject(err);
    }
    return defer.resolve(res);
  });
  return defer.promise;
};

globPaths = function(globs) {
  return function() {
    var p,
      _this = this;

    return Q.all((function() {
      var _i, _len, _results;

      _results = [];
      for (_i = 0, _len = globs.length; _i < _len; _i++) {
        p = globs[_i];
        _results.push(globPath(p));
      }
      return _results;
    })()).then(function(results) {
      var paths;

      paths = [];
      results.forEach(function(a) {
        return paths = paths.concat(a);
      });
      return paths;
    });
  };
};

loadSpecs = function(options) {
  return function(paths) {
    var p, _i, _len;

    if (options.verbose) {
      console.log("Load specs: " + paths + "\n");
    }
    for (_i = 0, _len = paths.length; _i < _len; _i++) {
      p = paths[_i];
      require(path.resolve('.', p));
    }
    return paths;
  };
};

getReporter = function(options) {
  var reporter;

  reporter = new spectacular.ConsoleReporter(options);
  reporter.on('message', function(event) {
    return util.print(event.target);
  });
  reporter.on('report', function(event) {
    return util.print(event.target);
  });
  return reporter;
};

loadFile = function(options) {
  var cache;

  cache = {};
  return function(file) {
    return Q.fcall(function() {
      var compile, fileContent;

      if (file in cache) {
        return cache[file];
      }
      fileContent = fs.readFileSync(file).toString();
      if (options.coffee && file.indexOf('.coffee') !== -1) {
        compile = require('coffee-script').compile;
        fileContent = compile(fileContent, {
          bare: true
        });
      }
      return cache[file] = fileContent;
    });
  };
};

exports.run = function(options) {
  var loadEndedAt, loadStartedAt;

  loadStartedAt = null;
  loadEndedAt = null;
  options.loadFile = loadFile(options);
  options.jQuery = require('jquery').create(null, '1.9');
  return loadSpectacular(options).then(function() {
    var reporter;

    reporter = getReporter(options);
    spectacular.env.runner.on('result', reporter.onResult);
    return spectacular.env.runner.on('end', reporter.onEnd);
  }).then(loadMatchers(options)).then(loadHelpers(options)).then(function() {
    return loadStartedAt = new Date();
  }).then(globPaths(options.globs)).then(loadSpecs(options)).then(function(paths) {
    loadEndedAt = new Date();
    spectacular.env.runner.loadStartedAt = loadStartedAt;
    spectacular.env.runner.loadEndedAt = loadEndedAt;
    spectacular.env.runner.paths = paths;
    return spectacular.env.run();
  }).fail(function(reason) {
    var reporter;

    if (spectacular.env != null) {
      reporter = getReporter(options);
      console.log(reporter.errorBadge("Spectacular failed"));
      return reporter.formatError(reason).then(function(msg) {
        return console.log(msg);
      });
    } else {
      return console.log(reason.stack);
    }
  });
};
