// Generated by CoffeeScript 1.6.2
var spectacular;

spectacular = {};

spectacular.factories || (spectacular.factories = {});

spectacular.factories.buildMethodsCache = {};

spectacular.factories.build = function(ctor, args) {
  var argumentsSignature, comma, f, n;

  f = spectacular.factories.buildMethodsCache[args.length] != null ? spectacular.factories.buildMethodsCache[args.length] : (argumentsSignature = '', comma = '', args.length > 0 ? (argumentsSignature = ((function() {
    var _i, _ref, _results;

    _results = [];
    for (n = _i = 0, _ref = args.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; n = 0 <= _ref ? ++_i : --_i) {
      _results.push("arg" + n);
    }
    return _results;
  })()).join(','), comma = ',') : void 0, spectacular.factories.buildMethodsCache[args.length] = new Function("ctor" + comma + argumentsSignature, "return new ctor(" + argumentsSignature + ");"));
  return f.apply(null, [ctor].concat(args));
};

spectacular.factories.factory = function(name, block) {};

global.build = spectacular.factories.build;

global.factory = spectacular.factories.factory;
