// Generated by CoffeeScript 1.6.2
var Runner, filename, fs, m, path, src, vm;

m = require('module');

fs = require('fs');

vm = require('vm');

path = require('path');

Runner = require('./runner');

filename = path.resolve(__dirname, 'spectacular.js');

src = fs.readFileSync(filename);

vm.runInThisContext(src, filename);

filename = path.resolve(__dirname, 'matchers.js');

src = fs.readFileSync(filename);

vm.runInThisContext(src, filename);

exports.run = function(options) {
  return new Runner(rootExampleGroup, options).run();
};
