// Generated by CoffeeScript 1.6.2
var k, spectacular, v, _ref;

spectacular = spectacular || {};

spectacular.matchers || (spectacular.matchers = {});

spectacular.matchers.exist = {
  assert: function(actual, notText) {
    this.description = "should" + notText + " exist";
    this.message = "Expected " + actual + notText + " to exist";
    return actual != null;
  }
};

spectacular.matchers.be = function(state) {
  return {
    assert: function(actual, notText) {
      this.description = "should" + notText + " be " + state;
      this.message = ("Expected " + actual + "." + state + notText + "      to be true but was " + actual[state]).replace(/\s+/g, ' ');
      return actual[state];
    }
  };
};

spectacular.matchers.equal = function(value) {
  return {
    assert: function(actual, notText) {
      this.description = "should" + notText + " be equal to " + value;
      this.message = "Expected " + actual + notText + " to be equal to " + value;
      return actual === value;
    }
  };
};

_ref = spectacular.matchers;
for (k in _ref) {
  v = _ref[k];
  global[k] = v;
}
