// Generated by CoffeeScript 1.6.3
var Q, SPECTACULAR_ROOT, exists, express, findHelpers, findMatchers, fs, generateSpecRunner, glob, globPath, globPaths, path, scriptNode, spawn, util, walk;

fs = require('fs');

Q = require('q');

glob = require('glob');

path = require('path');

express = require('express');

walk = require('walkdir');

util = require('util');

spawn = require('child_process').spawn;

exists = fs.exists || path.exists;

SPECTACULAR_ROOT = path.resolve(__dirname, '..');

findMatchers = function(options) {
  var defer, res;
  defer = Q.defer();
  res = [];
  if (options.noMatchers) {
    defer.resolve();
  } else {
    exists(options.matchersRoot, function(exist) {
      var emitter;
      if (exist) {
        emitter = walk(options.matchersRoot);
        emitter.on('file', function(p, stat) {
          return res.push(path.relative('.', p));
        });
        return emitter.on('end', function() {
          return defer.resolve(res);
        });
      } else {
        return defer.resolve([]);
      }
    });
  }
  return defer.promise;
};

findHelpers = function(options) {
  var defer, res;
  defer = Q.defer();
  res = [];
  if (options.noHelpers) {
    defer.resolve();
  } else {
    exists(options.helpersRoot, function(exist) {
      var emitter;
      if (exist) {
        emitter = walk(options.helpersRoot);
        emitter.on('file', function(p, stat) {
          return res.push(path.relative('.', p));
        });
        return emitter.on('end', function() {
          return defer.resolve(res);
        });
      } else {
        return defer.resolve([]);
      }
    });
  }
  return defer.promise;
};

globPath = function(p) {
  var defer;
  defer = Q.defer();
  glob(p, function(err, res) {
    if (err) {
      return defer.reject(err);
    }
    return defer.resolve(res);
  });
  return defer.promise;
};

globPaths = function(globs) {
  var p,
    _this = this;
  return Q.all((function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = globs.length; _i < _len; _i++) {
      p = globs[_i];
      _results.push(globPath(p));
    }
    return _results;
  })()).then(function(results) {
    var paths;
    paths = [];
    results.forEach(function(a) {
      return paths = paths.concat(a);
    });
    return paths;
  });
};

scriptNode = function(path) {
  return "<script type='text/javascript' src='" + path + "'></script>";
};

generateSpecRunner = function(options) {
  var paths;
  paths = ['assets/js/spectacular.js', 'assets/js/browser_reporter.js'];
  return findHelpers(options).then(function(helpers) {
    paths = paths.concat(helpers);
    return findMatchers(options);
  }).then(function(matchers) {
    paths = paths.concat(matchers);
    return globPaths(options.globs);
  }).then(function(specs) {
    return paths = paths.concat(specs);
  }).then(function() {
    return globPaths(options.sources);
  }).then(function(sources) {
    var p;
    return "<!doctype html>\n<html>\n  <head>\n    <script>\n      options = " + (util.inspect(options)) + ";\n      paths = " + (util.inspect(paths.slice(3))) + ";\n    </script>\n    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300' rel='stylesheet' type='text/css'>\n    <link rel=\"stylesheet\" href=\"assets/css/spectacular.css\"/>\n    <link rel=\"stylesheet\" href=\"http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.min.css\"/>\n    " + (((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = sources.length; _i < _len; _i++) {
        p = sources[_i];
        _results.push(scriptNode(p));
      }
      return _results;
    })()).join('\n')) + "\n    " + (((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = paths.length; _i < _len; _i++) {
        p = paths[_i];
        _results.push(scriptNode(p));
      }
      return _results;
    })()).join('\n')) + "\n  </head>\n  <body></body>\n</html>";
  });
};

exports.run = function(options) {
  var app, defer, phantom, port;
  defer = Q.defer();
  app = express();
  app.get('/', function(req, res) {
    return generateSpecRunner(options).then(function(html) {
      return res.send(html);
    });
  });
  app.use('/assets/js', express["static"](path.resolve(SPECTACULAR_ROOT, 'lib')));
  app.use('/assets/css', express["static"](path.resolve(SPECTACULAR_ROOT, 'css')));
  app.use('/', function(req, res, next) {
    var compile, content;
    content = fs.readFileSync(path.resolve("./" + req.url)).toString();
    if (/\.coffee$/.test(req.url) && options.coffee) {
      compile = require('coffee-script').compile;
      content = compile(content);
    }
    return res.send(content);
  });
  port = process.env.PORT || 5000;
  app.listen(port);
  console.log("  server listening on port " + (port.toString().cyan));
  if (options.phantomjs) {
    console.log("  running tests on phantomjs");
    phantom = spawn('phantomjs', ['./lib/spectacular_phantomjs.js']);
    phantom.stdout.on('data', function(data) {
      return util.print(data.toString());
    });
    phantom.stderr.on('data', function(data) {
      return util.print(data.toString());
    });
    phantom.on('exit', function(status) {
      return process.exit(status);
    });
  }
  return defer.promise;
};
