// Generated by CoffeeScript 1.6.2
var Q, http;

Q = require('q');

http = require('http');

exports.run = function(options) {
  var server;

  server = http.createServer(function(request, response) {
    console.log(request);
    return response.write('hello world');
  });
  server.listen(5000);
  return Q.defer().promise;
};
