// Generated by CoffeeScript 1.6.2
var exports, isCommonJS, k, nextTick, spectacular, utils, v,
  __slice = [].slice,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

String.prototype.capitalize = function() {
  return this.replace(/^(\w)/, function(m, c) {
    return c.toUpperCase();
  });
};

Function.prototype.include = function() {
  var excluded, k, mixin, mixins, v, _i, _len, _ref;

  mixins = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  excluded = ['constructor'];
  for (_i = 0, _len = mixins.length; _i < _len; _i++) {
    mixin = mixins[_i];
    _ref = mixin.prototype;
    for (k in _ref) {
      v = _ref[k];
      if (__indexOf.call(excluded, k) < 0) {
        this.prototype[k] = v;
      }
    }
    if (typeof mixin.included === "function") {
      mixin.included(this);
    }
  }
  return this;
};

Function.prototype.signature = function() {
  var re, _ref;

  re = /^function(\s+[a-zA-Z_][a-zA-Z0-9_]*)*\s*\(([^\)]+)\)/;
  return ((_ref = re.exec(this.toString())) != null ? _ref[2].split(/\s*,\s*/) : void 0) || [];
};

Function.prototype.getter = function(name, block) {
  return Object.defineProperty(this.prototype, name, {
    get: block,
    configurable: true,
    enumerable: true
  });
};

Function.prototype.setter = function(name, block) {
  return Object.defineProperty(this.prototype, name, {
    set: block,
    configurable: true,
    enumerable: true
  });
};

Function.prototype.accessor = function(name, options) {
  return Object.defineProperty(this.prototype, name, {
    get: options.get,
    set: options.set,
    configurable: true,
    enumerable: true
  });
};

spectacular = {};

isCommonJS = typeof window === "undefined";

if (isCommonJS) {
  exports = exports || {};
} else {
  exports = window;
}

exports.spectacular = spectacular;

spectacular.version = '0.0.1';

spectacular.global = (function() {
  if (typeof window !== 'undefined') {
    return window;
  }
  if (typeof global !== 'undefined') {
    return global;
  }
  return {};
})();

utils = spectacular.utils || (spectacular.utils = {});

spectacular.utils.squeeze = function(s) {
  return s.replace(/\s+/g, ' ');
};

spectacular.utils.keys = function(o) {
  var k, _results;

  _results = [];
  for (k in o) {
    _results.push(k);
  }
  return _results;
};

spectacular.utils.isArray = function(o) {
  return Object.prototype.toString.call(o) === '[object Array]';
};

spectacular.utils.fill = function(l, s) {
  var o;

  if (l == null) {
    l = 4;
  }
  if (s == null) {
    s = ' ';
  }
  o = '';
  while (o.length < l) {
    o = "" + o + s;
  }
  return o;
};

spectacular.utils.uniq = function(arr) {
  var newArr, v, _i, _len;

  newArr = [];
  for (_i = 0, _len = arr.length; _i < _len; _i++) {
    v = arr[_i];
    if (__indexOf.call(newArr, v) < 0) {
      newArr.push(v);
    }
  }
  return newArr;
};

spectacular.utils.andOrBut = function(bool) {
  if (bool) {
    return 'and';
  } else {
    return 'but';
  }
};

spectacular.utils.escapeDiff = function(s) {
  return utils.escape(s.replace(/<del>/g, '[[del]]').replace(/<\/del>/g, '[[/del]]').replace(/<ins>/g, '[[ins]]').replace(/<\/ins>/g, '[[/ins]]')).replace(/\[\[del\]\]/g, '<del>').replace(/\[\[\/del\]\]/g, '</del>').replace(/\[\[ins\]\]/g, '<ins>').replace(/\[\[\/ins\]\]/g, '</ins>');
};

spectacular.utils.escape = function(s) {
  var n;

  n = s;
  n = n.replace(/&/g, '&amp;');
  n = n.replace(/</g, '&lt;');
  n = n.replace(/>/g, '&gt;');
  n = n.replace(/"/g, '&quot;');
  return n;
};

spectacular.utils.unescape = function(s) {
  var n;

  n = s;
  n = n.replace(/&amp;/g, '&');
  n = n.replace(/&lt;/g, '<');
  n = n.replace(/&gt;/g, '>');
  n = n.replace(/&quot;/g, '"');
  return n;
};

spectacular.utils.indent = function(string, ind) {
  var i, s, _i, _ref;

  if (ind == null) {
    ind = 4;
  }
  s = '';
  for (i = _i = 0, _ref = ind - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
    s = "" + s + " ";
  }
  return "" + s + (string.replace(/\n/g, "\n" + s));
};

spectacular.utils.padRight = function(string, pad) {
  if (pad == null) {
    pad = 4;
  }
  string = string.toString();
  while (string.length < pad) {
    string = " " + string;
  }
  return string;
};

spectacular.utils.toggle = function(value, c1, c2) {
  if (value) {
    return c2;
  } else {
    return c1;
  }
};

spectacular.utils.TAGS = isCommonJS ? {
  delStart: '\x1B[31m',
  delEnd: '\x1B[39m',
  insStart: '\x1B[32m',
  insEnd: '\x1B[39m',
  space: ''
} : {
  delStart: '<del>',
  delEnd: '</del>',
  insStart: '<ins>',
  insEnd: '</ins>',
  space: ''
};

spectacular.utils.ins = function(str) {
  return utils.TAGS.insStart + str + utils.TAGS.insEnd;
};

spectacular.utils.del = function(str) {
  return utils.TAGS.delStart + str + utils.TAGS.delEnd;
};

spectacular.utils.diff = function(o, n) {
  var i, ns, os;

  ns = new Object();
  os = new Object();
  i = 0;
  while (i < n.length) {
    if (ns[n[i]] == null) {
      ns[n[i]] = {
        rows: new Array(),
        o: null
      };
    }
    ns[n[i]].rows.push(i);
    i++;
  }
  i = 0;
  while (i < o.length) {
    if (os[o[i]] == null) {
      os[o[i]] = {
        rows: new Array(),
        n: null
      };
    }
    os[o[i]].rows.push(i);
    i++;
  }
  for (i in ns) {
    if (ns[i].rows.length === 1 && typeof os[i] !== "undefined" && os[i].rows.length === 1) {
      n[ns[i].rows[0]] = {
        text: n[ns[i].rows[0]],
        row: os[i].rows[0]
      };
      o[os[i].rows[0]] = {
        text: o[os[i].rows[0]],
        row: ns[i].rows[0]
      };
    }
  }
  i = 0;
  while (i < n.length - 1) {
    if ((n[i].text != null) && (n[i + 1].text == null) && n[i].row + 1 < o.length && (o[n[i].row + 1].text == null) && n[i + 1] === o[n[i].row + 1]) {
      n[i + 1] = {
        text: n[i + 1],
        row: n[i].row + 1
      };
      o[n[i].row + 1] = {
        text: o[n[i].row + 1],
        row: i + 1
      };
    }
    i++;
  }
  i = n.length - 1;
  while (i > 0) {
    if ((n[i].text != null) && (n[i - 1].text == null) && n[i].row > 0 && (o[n[i].row - 1].text == null) && n[i - 1] === o[n[i].row - 1]) {
      n[i - 1] = {
        text: n[i - 1],
        row: n[i].row - 1
      };
      o[n[i].row - 1] = {
        text: o[n[i].row - 1],
        row: i - 1
      };
    }
    i--;
  }
  return {
    o: o,
    n: n
  };
};

spectacular.utils.stringDiff = function(o, n) {
  var i, nSpace, oSpace, out, pre, str;

  if ((n == null) || n.length === 0) {
    return utils.del(o);
  }
  if ((o == null) || o.length === 0) {
    return utils.ins(n);
  }
  o = String(o).replace(/\s+$/, "");
  n = String(n).replace(/\s+$/, "");
  out = utils.diff((o === "" ? [] : o.split(/\s+/)), (n === "" ? [] : n.split(/\s+/)));
  str = "";
  oSpace = o.match(/\s+/g);
  if (oSpace == null) {
    oSpace = [utils.TAGS.space];
  } else {
    oSpace.push(utils.TAGS.space);
  }
  nSpace = n.match(/\s+/g);
  if (nSpace == null) {
    nSpace = [utils.TAGS.space];
  } else {
    nSpace.push(utils.TAGS.space);
  }
  if (out.n.length === 0) {
    i = 0;
    while (i < out.o.length) {
      str += utils.del(utils.escape(out.o[i]) + oSpace[i]);
      i++;
    }
  } else {
    if (out.n[0].text == null) {
      n = 0;
      while (n < out.o.length && (out.o[n].text == null)) {
        str += utils.del(utils.escape(out.o[n]) + oSpace[n]);
        n++;
      }
    }
    i = 0;
    while (i < out.n.length) {
      if (out.n[i].text == null) {
        str += utils.ins(utils.escape(out.n[i]) + nSpace[i]);
      } else {
        pre = "";
        n = out.n[i].row + 1;
        while (n < out.o.length && (out.o[n].text == null)) {
          pre += utils.del(utils.escape(out.o[n]) + oSpace[n]);
          n++;
        }
        str += "" + out.n[i].text + nSpace[i] + pre;
      }
      i++;
    }
  }
  return str;
};

spectacular.utils.inspect = function(obj, depth) {
  var ind, k, v;

  if (depth == null) {
    depth = 1;
  }
  switch (typeof obj) {
    case 'string':
      return "'" + obj + "'";
    case 'number':
    case 'boolean':
      return "" + obj;
    case 'object':
      if (obj == null) {
        return 'null';
      }
      ind = utils.fill(depth * 2);
      if (utils.isArray(obj)) {
        if (obj.length === 0) {
          return '[]';
        }
        return "[\n" + (obj.map(function(o) {
          return ind + utils.inspect(o, depth + 1);
        }).join(',\n')) + "\n" + ind.slice(0, -2) + "]";
      } else {
        if (utils.keys(obj).length === 0) {
          return '{}';
        }
        return "{\n" + (((function() {
          var _results;

          _results = [];
          for (k in obj) {
            v = obj[k];
            _results.push("" + ind + k + ": " + (utils.inspect(v, depth + 1)));
          }
          return _results;
        })()).join(',\n')) + "\n" + ind.slice(0, -2) + "}";
      }
      break;
    case 'function':
      if (obj.name) {
        return obj.name;
      } else if (obj._name) {
        return obj._name;
      } else {
        return obj.toString();
      }
      break;
    default:
      return 'undefined';
  }
};

spectacular.utils.objectDiff = function(left, right, depth) {
  var a, allKeys, i, ind, k, key, l, p, prevInd, s, typeLeft, typeRight;

  if (depth == null) {
    depth = 1;
  }
  typeLeft = typeof left;
  typeRight = typeof right;
  if (typeLeft !== typeRight) {
    s = '';
    if (left != null) {
      s += utils.del(utils.inspect(left, depth));
    }
    if (right != null) {
      s += utils.ins(utils.inspect(right, depth));
    }
    return s;
  }
  switch (typeLeft) {
    case 'string':
      return utils.inspect(utils.stringDiff(left, right));
    case 'number':
    case 'boolean':
      return utils.stringDiff(left.toString(), right.toString());
    case 'object':
      if (utils.isArray(left) !== utils.isArray(right)) {
        return utils.del(utils.inspect(left, depth)) + utils.ins(utils.inspect(right, depth));
      }
      ind = utils.fill(depth * 2);
      prevInd = utils.fill((depth - 1) * 2);
      if (utils.isArray(left)) {
        l = Math.max(left.length, right.length);
        s = '[';
        a = (function() {
          var _i, _ref, _results;

          _results = [];
          for (i = _i = 0, _ref = l - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
            _results.push('\n' + ind + utils.objectDiff(left[i], right[i], depth + 1));
          }
          return _results;
        })();
        return s += a.join(',') + ("\n" + prevInd + "]");
      } else {
        allKeys = utils.uniq(utils.keys(left).concat(utils.keys(right)));
        s = "{";
        a = (function() {
          var _i, _len, _results;

          _results = [];
          for (_i = 0, _len = allKeys.length; _i < _len; _i++) {
            k = allKeys[_i];
            key = k + ': ';
            p = '';
            if (!right[k]) {
              p = utils.del("" + key + left[k]);
            } else if (!left[k]) {
              p = utils.ins("" + key + right[k]);
            } else {
              p = key + utils.objectDiff(left[k], right[k], depth + 1);
            }
            _results.push('\n' + ind + p);
          }
          return _results;
        })();
        return s += a.join(',') + ("\n" + prevInd + "}");
      }
  }
};

spectacular.utils.compare = function(actual, value, matcher, noMessage) {
  var i, k, v, _i, _len;

  if (noMessage == null) {
    noMessage = false;
  }
  switch (typeof value) {
    case 'object':
      if (utils.isArray(actual)) {
        if (!noMessage) {
          matcher.message = "" + matcher.message + "\n\n" + (utils.objectDiff(actual, value));
        }
        if (actual.length !== value.length) {
          return false;
        }
        for (i = _i = 0, _len = value.length; _i < _len; i = ++_i) {
          v = value[i];
          if (!utils.compare(actual[i], v, matcher, true)) {
            return false;
          }
        }
        return true;
      } else {
        if (!noMessage) {
          matcher.message = "" + matcher.message + "\n\n" + (utils.objectDiff(actual, value));
        }
        if (utils.keys(actual).length !== utils.keys(value).length) {
          return false;
        }
        for (k in value) {
          v = value[k];
          if (!utils.compare(actual[k], v, matcher, true)) {
            return false;
          }
        }
        return true;
      }
      break;
    case 'string':
      if (!noMessage) {
        matcher.message = "" + matcher.message + "\n\n'" + (utils.stringDiff(actual, value)) + "'";
      }
      return actual === value;
    default:
      return actual === value;
  }
};

spectacular.utils.findStateMethodOrProperty = function(obj, state) {
  var camelizedVersion, snakedVersion;

  camelizedVersion = "is" + (state.capitalize());
  snakedVersion = "is_" + state;
  if (obj[state] != null) {
    return state;
  } else if (obj[camelizedVersion] != null) {
    return camelizedVersion;
  } else if (obj[snakedVersion] != null) {
    return snakedVersion;
  } else {
    return null;
  }
};

for (k in utils) {
  v = utils[k];
  v._name = k;
}

spectacular.factories || (spectacular.factories = {});

spectacular.factories.buildMethodsCache = {};

spectacular.factories.build = function(ctor, args) {
  var argumentsSignature, comma, f, n;

  if (args == null) {
    args = [];
  }
  f = spectacular.factories.buildMethodsCache[args.length] != null ? spectacular.factories.buildMethodsCache[args.length] : (argumentsSignature = '', comma = '', args.length > 0 ? (argumentsSignature = ((function() {
    var _i, _ref, _results;

    _results = [];
    for (n = _i = 0, _ref = args.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; n = 0 <= _ref ? ++_i : --_i) {
      _results.push("arg" + n);
    }
    return _results;
  })()).join(','), comma = ',') : void 0, spectacular.factories.buildMethodsCache[args.length] = new Function("ctor" + comma + argumentsSignature, "return new ctor(" + argumentsSignature + ");"));
  return f.apply(null, [ctor].concat(args));
};

spectacular.factories.Set = (function() {
  function Set(property, value) {
    this.property = property;
    this.value = value;
  }

  Set.prototype.apply = function(instance) {
    if (typeof this.value === 'function') {
      return instance[this.property] = this.value();
    } else {
      return instance[this.property] = this.value;
    }
  };

  return Set;

})();

spectacular.factories.Trait = (function() {
  Trait.EXPOSED_PROPERTIES = 'set createWith'.split(/\s+/g);

  function Trait(name) {
    this.name = name;
    this.createWith = __bind(this.createWith, this);
    this.set = __bind(this.set, this);
    this.previous = {};
    this.setters = [];
  }

  Trait.prototype.set = function(property, value) {
    return this.setters.push(new spectacular.factories.Set(property, value));
  };

  Trait.prototype.createWith = function() {
    var arguments, _arguments;

    _arguments = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    this["arguments"] = _arguments;
  };

  Trait.prototype.applySet = function(instance) {
    return this.setters.forEach(function(setter) {
      return setter.apply(instance);
    });
  };

  Trait.prototype.load = function() {
    var _global,
      _this = this;

    _global = spectacular.global;
    return this.constructor.EXPOSED_PROPERTIES.forEach(function(k) {
      if (_global[k] != null) {
        _this.previous[k] = _global[k];
      }
      return _global[k] = _this[k];
    });
  };

  Trait.prototype.unload = function() {
    var _global,
      _this = this;

    _global = spectacular.global;
    return this.constructor.EXPOSED_PROPERTIES.forEach(function(k) {
      if (_this.previous[k] != null) {
        return _global[k] = _this.previous[k];
      } else {
        return delete _global[k];
      }
    });
  };

  return Trait;

})();

spectacular.factories.Factory = (function(_super) {
  __extends(Factory, _super);

  Factory.EXPOSED_PROPERTIES = 'set trait createWith'.split(/\s+/g);

  function Factory(name, _class) {
    this["class"] = _class;
    this.trait = __bind(this.trait, this);
    Factory.__super__.constructor.call(this, name);
    this.traits = {};
  }

  Factory.prototype.trait = function(name, block) {
    var trait, _base;

    trait = (_base = this.traits)[name] || (_base[name] = new spectacular.factories.Trait(name));
    trait.load();
    block.call(trait);
    return trait.unload();
  };

  Factory.prototype.build = function(traits, options) {
    var args, instance, trait, _i, _j, _len, _len1;

    if (options == null) {
      options = {};
    }
    for (_i = 0, _len = traits.length; _i < _len; _i++) {
      trait = traits[_i];
      args = this.traits[trait]["arguments"];
    }
    args || (args = this["arguments"] || []);
    instance = build(this["class"], args);
    this.applySet(instance);
    for (_j = 0, _len1 = traits.length; _j < _len1; _j++) {
      trait = traits[_j];
      this.traits[trait].applySet(instance);
    }
    for (k in options) {
      v = options[k];
      instance[k] = v;
    }
    return instance;
  };

  return Factory;

})(spectacular.factories.Trait);

spectacular.factoriesCache = {};

spectacular.factories.factory = function(name, options, block) {
  var cache, fct;

  cache = spectacular.factoriesCache;
  fct = cache[name] || (cache[name] = new spectacular.factories.Factory(name, options["class"]));
  fct.load();
  block.call(fct);
  return fct.unload();
};

spectacular.factories.create = function() {
  var fct, name, options, traits, _i;

  name = arguments[0], traits = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), options = arguments[_i++];
  if (name == null) {
    throw new Error('no factory name provided');
  }
  if (typeof options === 'string') {
    traits.push(options);
    options = null;
  }
  fct = spectacular.factoriesCache[name];
  if (fct == null) {
    throw new Error("missing factory " + name);
  }
  return fct.build(traits, options);
};

spectacular.HasAncestors = (function() {
  function HasAncestors() {}

  HasAncestors.included = function(ctor) {
    ctor.getter('ancestors', function() {
      var ancestors, parent;

      ancestors = [];
      parent = this.parent;
      while (parent) {
        ancestors.push(parent);
        parent = parent.parent;
      }
      return ancestors;
    });
    return ctor.ancestorsScope = function(name, block) {
      return this.getter(name, function() {
        return this.ancestors.filter(block);
      });
    };
  };

  return HasAncestors;

})();

spectacular.HasCollection = function(plural, singular) {
  var ConcreteHasCollection, capitalizedPlural, capitalizedSingular, mixin;

  capitalizedSingular = singular.capitalize();
  capitalizedPlural = plural.capitalize();
  mixin = ConcreteHasCollection = (function() {
    function ConcreteHasCollection() {}

    ConcreteHasCollection.included = function(ctor) {
      return ctor["" + plural + "Scope"] = function(name, block) {
        return ctor.getter(name, function() {
          return this[plural].filter(block);
        });
      };
    };

    return ConcreteHasCollection;

  })();
  mixin.prototype["add" + capitalizedSingular] = function() {
    var item, items, _i, _len, _results;

    items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      item = items[_i];
      if (__indexOf.call(this[plural], item) < 0) {
        _results.push(this[plural].push(item));
      }
    }
    return _results;
  };
  mixin.prototype["remove" + capitalizedSingular] = function() {
    var item, items, newArray, _i, _len, _ref;

    items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    newArray = [];
    _ref = this[plural];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      if (__indexOf.call(items, item) < 0) {
        newArray.push(item);
      }
    }
    return this[plural] = newArray;
  };
  mixin.prototype["" + singular + "At"] = function(index) {
    return this[plural][index];
  };
  mixin.prototype["find" + capitalizedSingular] = mixin.prototype["indexOf" + capitalizedSingular] = function(item) {
    return this[plural].indexOf(item);
  };
  mixin.prototype["has" + capitalizedSingular] = mixin.prototype["contains" + capitalizedSingular] = function(item) {
    return this[plural].indexOf(item) !== -1;
  };
  mixin.prototype["" + plural + "Length"] = mixin.prototype["" + plural + "Size"] = mixin.prototype["" + plural + "Count"] = function() {
    return this[plural].length;
  };
  return mixin;
};

spectacular.HasNestedCollection = function(name, options) {
  var ConcreteHasNestedCollection, mixin, through;

  if (options == null) {
    options = {};
  }
  through = options.through;
  if (through == null) {
    throw new Error('missing through option');
  }
  mixin = ConcreteHasNestedCollection = (function() {
    function ConcreteHasNestedCollection() {}

    ConcreteHasNestedCollection.included = function(ctor) {
      ctor["" + name + "Scope"] = function(scopeName, block) {
        return ctor.getter(scopeName, function() {
          return this[name].filter(block);
        });
      };
      return ctor.getter(name, function() {
        var items;

        items = [];
        this[through].forEach(function(item) {
          items.push(item);
          if (item[name] != null) {
            return items = items.concat(item[name]);
          }
        });
        return items;
      });
    };

    return ConcreteHasNestedCollection;

  })();
  return mixin;
};

spectacular.FollowUpProperty = function(property) {
  var ConcreteFollowUpProperty, capitalizedProperty, privateProperty;

  capitalizedProperty = property.capitalize();
  privateProperty = "own" + capitalizedProperty;
  return ConcreteFollowUpProperty = (function() {
    function ConcreteFollowUpProperty() {}

    ConcreteFollowUpProperty.included = function(ctor) {
      return ctor.accessor(property, {
        get: function() {
          var _ref;

          return this[privateProperty] || ((_ref = this.parent) != null ? _ref[property] : void 0);
        },
        set: function(value) {
          return this[privateProperty] = value;
        }
      });
    };

    return ConcreteFollowUpProperty;

  })();
};

spectacular.MergeUpProperty = function(property) {
  var ConcreteMergeUpProperty, capitalizedProperty, privateProperty;

  capitalizedProperty = property.capitalize();
  privateProperty = "own" + capitalizedProperty;
  return ConcreteMergeUpProperty = (function() {
    function ConcreteMergeUpProperty() {}

    ConcreteMergeUpProperty.included = function(ctor) {
      return ctor.accessor(property, {
        get: function() {
          var a;

          a = this[privateProperty];
          if (this.parent != null) {
            a = this.parent[property].concat(a);
          }
          return a;
        },
        set: function(value) {
          return this[privateProperty] = value;
        }
      });
    };

    return ConcreteMergeUpProperty;

  })();
};

spectacular.Describable = (function() {
  function Describable() {}

  Describable.included = function(ctor) {
    return ctor.getter('description', function() {
      var space, _ref;

      if (((_ref = this.parent) != null ? _ref.description : void 0) != null) {
        space = '';
        if (!this.noSpaceBeforeDescription) {
          space = ' ';
        }
        return "" + this.parent.description + space + this.ownDescription;
      } else {
        return this.ownDescription;
      }
    });
  };

  return Describable;

})();

spectacular.Event = (function() {
  function Event(name, target) {
    this.name = name;
    this.target = target;
  }

  return Event;

})();

spectacular.EventDispatcher = (function() {
  function EventDispatcher() {}

  EventDispatcher.prototype.on = function(event, callback) {
    var _base;

    this.listeners || (this.listeners = {});
    (_base = this.listeners)[event] || (_base[event] = []);
    if (__indexOf.call(this.listeners[event], callback) < 0) {
      return this.listeners[event].push(callback);
    }
  };

  EventDispatcher.prototype.off = function(event, callback) {
    var _ref;

    if ((((_ref = this.listeners) != null ? _ref[event] : void 0) != null) && __indexOf.call(this.listeners[event], callback) >= 0) {
      return this.listeners[event].splice(this.listeners[event].indexOf(callback), 1);
    }
  };

  EventDispatcher.prototype.hasListener = function(event) {
    var _ref;

    return (((_ref = this.listeners) != null ? _ref[event] : void 0) != null) && this.listeners[event].length > 0;
  };

  EventDispatcher.prototype.dispatch = function(event) {
    var _ref, _ref1;

    return (_ref = this.listeners) != null ? (_ref1 = _ref[event.name]) != null ? _ref1.forEach(function(listener) {
      return listener(event);
    }) : void 0 : void 0;
  };

  return EventDispatcher;

})();

spectacular.Promise = (function() {
  Promise.unit = function(value) {
    var promise;

    if (value == null) {
      value = 0;
    }
    promise = new spectacular.Promise;
    promise.resolve(value);
    return promise;
  };

  Promise.all = function(promises) {
    var promise, results, solved;

    promise = new spectacular.Promise;
    solved = 0;
    results = [];
    promises.forEach(function(p) {
      return p.then(function(value) {
        solved++;
        results[promises.indexOf(p)] = value;
        if (solved === promises.length) {
          return promise.resolve(results);
        }
      }).fail(function(reason) {
        return promise.reject(reason);
      });
    });
    return promise;
  };

  function Promise() {
    this.pending = true;
    this.fulfilled = null;
    this.value = void 0;
    this.fulfilledHandlers = [];
    this.errorHandlers = [];
    this.progressHandlers = [];
  }

  Promise.prototype.isPending = function() {
    return this.pending;
  };

  Promise.prototype.isResolved = function() {
    return !this.pending;
  };

  Promise.prototype.isFulfilled = function() {
    return !this.pending && this.fulfilled;
  };

  Promise.prototype.isRejected = function() {
    return !this.pending && !this.fulfilled;
  };

  Promise.prototype.then = function(fulfilledHandler, errorHandler, progressHandler) {
    var e, f, promise;

    promise = new spectacular.Promise;
    f = function(value) {
      var err, res;

      try {
        res = typeof fulfilledHandler === "function" ? fulfilledHandler(value) : void 0;
      } catch (_error) {
        err = _error;
        promise.reject(err);
        return;
      }
      if ((res != null ? res.then : void 0) != null) {
        return res.then(function(value) {
          return promise.resolve(value);
        }).fail(function(reason) {
          return promise.reject(reason);
        });
      } else {
        return promise.resolve(res);
      }
    };
    e = function(reason) {
      if (typeof errorHandler === "function") {
        errorHandler(reason);
      }
      return promise.reject(reason);
    };
    if (this.pending) {
      this.fulfilledHandlers.push(f);
      this.errorHandlers.push(e);
      if (progressHandler != null) {
        this.progressHandlers.push(progressHandler);
      }
    } else {
      if (this.fulfilled) {
        f(this.value);
      } else {
        e(this.reason);
      }
    }
    return promise;
  };

  Promise.prototype.fail = function(errorHandler) {
    return this.then((function() {}), errorHandler);
  };

  Promise.prototype.resolve = function(value) {
    this.value = value;
    if (!this.pending) {
      return;
    }
    this.fulfilled = true;
    this.notifyHandlers();
    return this.pending = false;
  };

  Promise.prototype.reject = function(reason) {
    if (!this.pending) {
      return;
    }
    this.reason = reason;
    this.fulfilled = false;
    this.notifyHandlers();
    return this.pending = false;
  };

  Promise.prototype.notifyHandlers = function() {
    var handler, _i, _j, _len, _len1, _ref, _ref1, _results, _results1;

    if (!this.pending) {
      return;
    }
    if (this.fulfilled) {
      _ref = this.fulfilledHandlers;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        handler = _ref[_i];
        _results.push(handler(this.value));
      }
      return _results;
    } else {
      _ref1 = this.errorHandlers;
      _results1 = [];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        handler = _ref1[_j];
        _results1.push(handler(this.reason));
      }
      return _results1;
    }
  };

  return Promise;

})();

spectacular.AsyncPromise = (function(_super) {
  __extends(AsyncPromise, _super);

  function AsyncPromise() {
    this.run = __bind(this.run, this);    this.interval = null;
    this.timeout = 5000;
    this.message = 'Timed out';
    AsyncPromise.__super__.constructor.call(this);
  }

  AsyncPromise.prototype.run = function() {
    var lastTime,
      _this = this;

    lastTime = new Date();
    return this.interval = setInterval(function() {
      if (new Date() - lastTime >= _this.timeout) {
        return _this.reject(new Error(_this.message));
      }
    }, 10);
  };

  AsyncPromise.prototype.reject = function(reason) {
    clearInterval(this.interval);
    return AsyncPromise.__super__.reject.call(this, reason);
  };

  AsyncPromise.prototype.resolve = function(value) {
    clearInterval(this.interval);
    return AsyncPromise.__super__.resolve.call(this, value);
  };

  AsyncPromise.prototype.rejectAfter = function(timeout, message) {
    this.timeout = timeout;
    this.message = message;
  };

  return AsyncPromise;

})(spectacular.Promise);

spectacular.Expectation = (function() {
  function Expectation(example, actual, matcher, not, callstack) {
    this.example = example;
    this.actual = actual;
    this.matcher = matcher;
    this.not = not != null ? not : false;
    this.callstack = callstack;
    this.createMessage = __bind(this.createMessage, this);
    this.assert = __bind(this.assert, this);
  }

  Expectation.prototype.assert = function() {
    var promise, timeout,
      _this = this;

    promise = new spectacular.Promise;
    timeout = null;
    spectacular.Promise.unit().then(function() {
      timeout = setTimeout(function() {
        _this.success = false;
        _this.trace = new Error('matcher timed out');
        _this.message = _this.matcher.message;
        _this.description = _this.matcher.description;
        return promise.resolve(_this.success);
      }, _this.matcher.timeout || 5000);
      return _this.matcher.assert(_this.actual, _this.not ? ' not' : '');
    }).then(function(success) {
      _this.success = success;
      clearTimeout(timeout);
      if (_this.not) {
        _this.success = !_this.success;
      }
      _this.createMessage();
      return promise.resolve(_this.success);
    }).fail(function(trace) {
      _this.trace = trace;
      clearTimeout(timeout);
      _this.success = false;
      if (_this.matcher.message == null) {
        _this.matcher.message = _this.trace.message;
      }
      if (_this.matcher.description == null) {
        _this.matcher.description = '';
      }
      return promise.reject(_this.trace);
    });
    return promise;
  };

  Expectation.prototype.createMessage = function() {
    var specIndex, stack;

    this.message = this.matcher.message;
    if (!this.success && (this.trace == null)) {
      if (this.callstack.stack != null) {
        stack = this.callstack.stack.split('\n');
        specIndex = spectacular.env.runner.findSpecFileInStack(stack);
        if (specIndex !== -1) {
          this.callstack.stack = stack.slice(specIndex).join('\n');
        }
      }
      this.trace = this.callstack;
    }
    this.description = this.matcher.description;
    return this.fullDescription = "" + this.example.description + " " + this.matcher.description;
  };

  return Expectation;

})();

spectacular.ExampleResult = (function() {
  var _addExpectation;

  ExampleResult.include(spectacular.HasCollection('expectations', 'expectation'));

  function ExampleResult(example, state) {
    this.example = example;
    this.state = state;
    this.expectations = [];
    this.promise = spectacular.Promise.unit();
  }

  ExampleResult.prototype.hasFailures = function() {
    return this.expectations.some(function(e) {
      return !e.success;
    });
  };

  _addExpectation = ExampleResult.prototype.addExpectation;

  ExampleResult.prototype.addExpectation = function(expectation) {
    var successHandler,
      _this = this;

    successHandler = function() {
      return expectation.assert().fail(function(e) {
        return _this.example.error(e);
      });
    };
    this.promise = this.promise.then(successHandler);
    return _addExpectation.call(this, expectation);
  };

  return ExampleResult;

})();

spectacular.Example = (function() {
  Example.include(spectacular.HasAncestors);

  Example.include(spectacular.Describable);

  Example.include(spectacular.FollowUpProperty('subjectBlock'));

  Example.include(spectacular.FollowUpProperty('cascading'));

  Example.include(spectacular.MergeUpProperty('beforeHooks'));

  Example.include(spectacular.MergeUpProperty('afterHooks'));

  Example.include(spectacular.MergeUpProperty('dependencies'));

  function Example(block, ownDescription, parent) {
    this.block = block;
    this.ownDescription = ownDescription != null ? ownDescription : '';
    this.parent = parent;
    this.executeExpectations = __bind(this.executeExpectations, this);
    this.reject = __bind(this.reject, this);
    this.resolve = __bind(this.resolve, this);
    if (this.ownDescription === '') {
      this.noSpaceBeforeDescription = true;
    }
    this.beforeHooks = [];
    this.afterHooks = [];
    this.dependencies = [];
    this.cascading = null;
  }

  Example.getter('subject', function() {
    var _ref;

    return this.__subject || (this.__subject = (_ref = this.subjectBlock) != null ? _ref.call(this.context) : void 0);
  });

  Example.getter('finished', function() {
    var _ref;

    return (_ref = this.examplePromise) != null ? _ref.isResolved() : void 0;
  });

  Example.getter('failed', function() {
    var _ref;

    return (_ref = this.examplePromise) != null ? _ref.isRejected() : void 0;
  });

  Example.getter('succeed', function() {
    var _ref;

    return (_ref = this.examplePromise) != null ? _ref.isFulfilled() : void 0;
  });

  Example.getter('reason', function() {
    var _ref;

    return this.afterReason || ((_ref = this.examplePromise) != null ? _ref.reason : void 0);
  });

  Example.getter('duration', function() {
    if ((this.runEndedAt != null) && (this.runStartedAt != null)) {
      return this.runEndedAt.getTime() - this.runStartedAt.getTime();
    } else {
      return 0;
    }
  });

  Example.getter('fullDescription', function() {
    var expectationsDescriptions, last;

    expectationsDescriptions = this.result.expectations.map(function(e) {
      return e.description;
    });
    if (expectationsDescriptions.length > 1) {
      last = expectationsDescriptions.pop();
      expectationsDescriptions = expectationsDescriptions.join(', ');
      expectationsDescriptions += " and " + last;
    } else {
      expectationsDescriptions = expectationsDescriptions.toString();
    }
    return "" + this.description + " " + expectationsDescriptions;
  });

  Example.ancestorsScope('identifiedAncestors', function(e) {
    return e.options.id != null;
  });

  Example.prototype.pending = function() {
    var _ref;

    if ((_ref = this.examplePromise) != null ? _ref.pending : void 0) {
      this.result.state = 'pending';
      return this.examplePromise.resolve();
    }
  };

  Example.prototype.skip = function() {
    var _ref;

    if ((_ref = this.examplePromise) != null ? _ref.pending : void 0) {
      this.result.state = 'skipped';
      return this.examplePromise.reject(new Error('Skipped'));
    }
  };

  Example.prototype.resolve = function() {
    var _ref;

    if ((_ref = this.examplePromise) != null ? _ref.pending : void 0) {
      if (this.result.hasFailures()) {
        this.result.state = 'failure';
        return this.examplePromise.reject();
      } else if (this.result.expectationsCount() === 0) {
        this.result.state = 'pending';
        return this.examplePromise.resolve();
      } else {
        this.result.state = 'success';
        return this.examplePromise.resolve();
      }
    }
  };

  Example.prototype.reject = function(reason) {
    var _ref;

    if ((_ref = this.examplePromise) != null ? _ref.pending : void 0) {
      this.result.state = 'failure';
      return this.examplePromise.reject(reason);
    }
  };

  Example.prototype.error = function(reason) {
    var _ref;

    if ((_ref = this.examplePromise) != null ? _ref.pending : void 0) {
      this.result.state = 'errored';
      return this.examplePromise.reject(reason);
    }
  };

  Example.prototype.createContext = function() {
    var context,
      _this = this;

    context = {};
    Object.defineProperty(context, 'subject', {
      get: function() {
        return _this.subject;
      }
    });
    return context;
  };

  Example.prototype.dependenciesMet = function() {
    return true;
  };

  Example.prototype.run = function() {
    var afterPromise,
      _this = this;

    this.runStartedAt = new Date();
    this.context = this.createContext();
    this.examplePromise = new spectacular.Promise;
    this.result = new spectacular.ExampleResult(this);
    if (!this.dependenciesMet()) {
      this.skip();
      return this.examplePromise;
    }
    afterPromise = new spectacular.Promise;
    this.runBefore(function(err) {
      _this.runEndedAt = new Date();
      if (err != null) {
        return _this.error(err);
      }
      return _this.executeBlock();
    });
    this.examplePromise.then(function() {
      return _this.runAfter(function(err) {
        _this.runEndedAt = new Date();
        if (err != null) {
          return _this.handleAfterError(err, afterPromise);
        }
        return afterPromise.resolve();
      });
    });
    this.examplePromise.fail(function(reason) {
      return _this.runAfter(function(err) {
        _this.runEndedAt = new Date();
        if (err != null) {
          return _this.handleAfterError(err, afterPromise);
        }
        return afterPromise.reject(reason);
      });
    });
    return afterPromise;
  };

  Example.prototype.handleAfterError = function(error, promise) {
    this.result.state = 'errored';
    this.afterReason = error;
    return promise.reject(error);
  };

  Example.prototype.runBefore = function(callback) {
    var befores;

    befores = this.beforeHooks.concat();
    return this.runHooks(befores, callback);
  };

  Example.prototype.runAfter = function(callback) {
    var afters;

    afters = this.afterHooks.concat();
    return this.runHooks(afters, callback);
  };

  Example.prototype.runHooks = function(hooks, callback) {
    var next,
      _this = this;

    next = function(err) {
      if (err != null) {
        return callback(err);
      }
      if (hooks.length === 0) {
        return callback();
      } else {
        return _this.executeHook(hooks.shift(), next);
      }
    };
    return next();
  };

  Example.prototype.executeHook = function(hook, next) {
    var async, e,
      _this = this;

    try {
      if (this.acceptAsync(hook)) {
        async = new spectacular.AsyncPromise;
        async.then(function() {
          return next();
        });
        async.fail(function(reason) {
          return next(reason);
        });
        async.run();
        return hook.call(this.context, async);
      } else {
        hook.call(this.context);
        return next();
      }
    } catch (_error) {
      e = _error;
      return next(e);
    }
  };

  Example.prototype.executeBlock = function() {
    var async, e;

    if (this.block == null) {
      return this.pending();
    }
    try {
      if (this.acceptAsync(this.block)) {
        async = new spectacular.AsyncPromise;
        async.then(this.executeExpectations, this.reject);
        async.run();
        return this.block.call(this.context, async);
      } else {
        this.block.call(this.context);
        return this.executeExpectations();
      }
    } catch (_error) {
      e = _error;
      return this.error(e);
    }
  };

  Example.prototype.executeExpectations = function() {
    return this.result.promise.then(this.resolve, this.reject);
  };

  Example.prototype.toString = function() {
    return "[Example(" + this.description + ")]";
  };

  Example.prototype.acceptAsync = function(func) {
    return func.signature().length === 1;
  };

  return Example;

})();

spectacular.ExampleGroup = (function(_super) {
  __extends(ExampleGroup, _super);

  ExampleGroup.include(spectacular.HasCollection('children', 'child'));

  ExampleGroup.include(spectacular.HasNestedCollection('descendants', {
    through: 'children'
  }));

  ExampleGroup.childrenScope('exampleGroups', function(e) {
    return e.children != null;
  });

  ExampleGroup.childrenScope('examples', function(e) {
    return e.children == null;
  });

  ExampleGroup.descendantsScope('allExamples', function(e) {
    return e.children == null;
  });

  ExampleGroup.descendantsScope('identifiedExamples', function(e) {
    var _ref;

    return ((_ref = e.options) != null ? _ref.id : void 0) != null;
  });

  ExampleGroup.getter('identifiedExamplesMap', function() {
    var e, res, _i, _len, _ref;

    res = {};
    _ref = this.identifiedExamples;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      e = _ref[_i];
      res[e.options.id] = e;
    }
    return res;
  });

  ExampleGroup.getter('finished', function() {
    return this.allExamples.every(function(e) {
      return e.finished;
    });
  });

  ExampleGroup.getter('failed', function() {
    return this.allExamples.some(function(e) {
      return e.failed;
    });
  });

  ExampleGroup.getter('succeed', function() {
    return !this.failed;
  });

  ExampleGroup.getter('examplesSuceed', function() {
    return this.examples.every(function(e) {
      return e.succeed;
    });
  });

  function ExampleGroup(block, desc, parent, options) {
    var original, owner, subject, type,
      _this = this;

    this.parent = parent;
    this.options = options != null ? options : {};
    subject = null;
    switch (typeof desc) {
      case 'string':
        if (desc.indexOf('.') === 0) {
          this.noSpaceBeforeDescription = true;
          owner = this.subject;
          subject = owner != null ? owner[desc.replace('.', '')] : void 0;
          if (typeof subject === 'function') {
            original = subject;
            subject = function() {
              return original.apply(owner, arguments);
            };
          }
          this.subjectBlock = function() {
            return subject;
          };
        } else if (desc.indexOf('::') === 0) {
          this.noSpaceBeforeDescription = true;
          type = typeof this.subjectBlock === "function" ? this.subjectBlock() : void 0;
          this.subjectBlock = function() {
            if (type) {
              owner = build(type, _this.parameters || []);
              return function() {
                return owner[desc.replace('::', '')].apply(owner, arguments);
              };
            }
          };
        } else {
          if (this.parent.description === '') {
            this.noSpaceBeforeDescription = true;
          }
        }
        break;
      default:
        this.noSpaceBeforeDescription = true;
        subject = desc;
        this.subjectBlock = function() {
          return subject;
        };
        desc = (subject != null ? subject.name : void 0) || (subject != null ? subject._name : void 0) || (subject != null ? subject.toString() : void 0) || '';
    }
    ExampleGroup.__super__.constructor.call(this, block, desc, this.parent);
    this.children = [];
  }

  ExampleGroup.prototype.run = function() {};

  ExampleGroup.prototype.executeBlock = function() {
    if (this.block == null) {
      return it(function() {
        return pending();
      });
    }
    return this.block.call(this);
  };

  ExampleGroup.prototype.toString = function() {
    return "[ExampleGroup(" + this.description + ")]";
  };

  return ExampleGroup;

})(spectacular.Example);

nextTick = (typeof process !== "undefined" && process !== null ? process.setImmediate : void 0) || (typeof process !== "undefined" && process !== null ? process.nextTick : void 0) || function(callback) {
  return setTimeout(callback, 0);
};

spectacular.Runner = (function() {
  Runner.include(spectacular.EventDispatcher);

  function Runner(root, options, env) {
    this.root = root;
    this.options = options;
    this.env = env;
    this.notifyEnd = __bind(this.notifyEnd, this);
    this.nextExample = __bind(this.nextExample, this);
    this.executeSpecs = __bind(this.executeSpecs, this);
    this.register = __bind(this.register, this);
    this.registerSpecs = __bind(this.registerSpecs, this);
    this.run = __bind(this.run, this);
    this.results = [];
    this.examples = [];
    this.stack = [];
  }

  Runner.prototype.run = function() {
    var promise,
      _this = this;

    return promise = spectacular.Promise.unit().then(function() {
      return _this.specsStartedAt = new Date();
    }).then(this.registerSpecs).then(this.executeSpecs).then(function() {
      return _this.specsEndedAt = new Date();
    }).then(this.notifyEnd).then(function() {
      if (_this.hasFailures()) {
        return 1;
      } else {
        return 0;
      }
    });
  };

  Runner.prototype.findSpecFileInStack = function(stack) {
    var i, l, p, _i, _j, _len, _len1, _ref;

    _ref = this.paths;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      p = _ref[_i];
      for (i = _j = 0, _len1 = stack.length; _j < _len1; i = ++_j) {
        l = stack[i];
        if (l.indexOf(p) !== -1) {
          return i;
        }
      }
    }
    return -1;
  };

  Runner.prototype.registerSpecs = function() {
    var example, _i, _len, _ref, _results;

    _ref = this.root.allExamples;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      example = _ref[_i];
      _results.push(this.register(example));
    }
    return _results;
  };

  Runner.prototype.register = function(example) {
    this.handleDependencies(example);
    if (__indexOf.call(this.stack, example) < 0) {
      return this.stack.push(example);
    }
  };

  Runner.prototype.handleDependencies = function(example) {
    var cascading, cascadingSucceed, dep, dependencies, dependenciesSucceed, dependency, s, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;

    if (__indexOf.call(this.stack, example) >= 0) {
      return;
    }
    dependencies = [];
    cascading = null;
    dependenciesSucceed = null;
    cascadingSucceed = null;
    if (example.dependencies.length > 0) {
      _ref = example.dependencies;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        dep = _ref[_i];
        dependency = this.root.identifiedExamplesMap[dep];
        if (dependency != null) {
          this.checkDependency(example, dependency);
          dependencies.push(dependency);
          if (dependency.children != null) {
            _ref1 = dependency.allExamples;
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              s = _ref1[_j];
              this.register(s);
            }
          } else {
            this.register(dependency);
          }
        } else {
          throw new Error("unmet dependency " + dep + " for example " + example);
        }
      }
      dependenciesSucceed = function() {
        return dependencies.every(function(e) {
          return e.succeed;
        });
      };
    }
    if (example.cascading != null) {
      _ref2 = example.cascading.examples;
      for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
        s = _ref2[_k];
        this.register(s);
      }
      cascadingSucceed = function() {
        return example.cascading.examplesSuceed;
      };
    }
    if (dependenciesSucceed != null) {
      if (cascadingSucceed != null) {
        return example.dependenciesMet = function() {
          return dependenciesSucceed() && cascadingSucceed();
        };
      } else {
        return example.dependenciesMet = dependenciesSucceed;
      }
    } else if (cascadingSucceed != null) {
      return example.dependenciesMet = cascadingSucceed;
    }
  };

  Runner.prototype.checkDependency = function(example, dependency) {
    if (__indexOf.call(example.ancestors, dependency) >= 0) {
      throw new Error("" + example + " can't depends on ancestor " + dependency);
    }
    return this.checkCircularity(example, dependency);
  };

  Runner.prototype.checkCircularity = function(example, dependency) {
    var currentParents, dep, depParents, id, _i, _j, _len, _len1, _ref, _results;

    currentParents = example.identifiedAncestors.map(function(a) {
      return a.options.id;
    });
    depParents = dependency.identifiedAncestors.map(function(a) {
      return a.options.id;
    }).concat(dependency.options.id);
    for (_i = 0, _len = currentParents.length; _i < _len; _i++) {
      id = currentParents[_i];
      if (__indexOf.call(depParents, id) >= 0) {
        throw new Error("circular dependencies between " + example + " and " + dependency);
      }
    }
    if (dependency.dependencies.length > 0) {
      _ref = dependency.dependencies;
      _results = [];
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        dep = _ref[_j];
        dependency = this.root.identifiedExamplesMap[dep];
        if (dependency != null) {
          _results.push(this.checkCircularity(example, dependency));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  };

  Runner.prototype.executeSpecs = function() {
    var promise;

    promise = new spectacular.Promise;
    this.nextExample(promise);
    return promise;
  };

  Runner.prototype.nextExample = function(defer) {
    var _this = this;

    return nextTick(function() {
      var nextExample;

      if (_this.stack.length === 0) {
        return defer.resolve();
      } else {
        nextExample = _this.stack.shift();
        _this.env.currentExample = nextExample;
        return nextExample.run().then(function() {
          _this.handleResult(nextExample);
          return _this.nextExample(defer);
        }).fail(function(reason) {
          _this.handleResult(nextExample);
          return _this.nextExample(defer);
        });
      }
    });
  };

  Runner.prototype.handleResult = function(example) {
    this.dispatch(new spectacular.Event('result', example));
    return this.env.currentExample = null;
  };

  Runner.prototype.notifyEnd = function() {
    return this.dispatch(new spectacular.Event('end', this));
  };

  Runner.prototype.hasFailures = function() {
    return this.root.allExamples.some(function(e) {
      var _ref;

      return (_ref = e.result.state) === 'skipped' || _ref === 'failure' || _ref === 'errored';
    });
  };

  return Runner;

})();

spectacular.Environment = (function() {
  Environment.prototype.exposedMethods = 'it xit describe xdescribe context xcontext\
    before after given subject its itsInstance\
    itsReturn withParameters fail pending success\
    skip should shouldnt dependsOn spyOn the\
    withArguments whenPass fixture specify';

  Environment.prototype.exposedSpectacularMethods = {
    build: spectacular.factories.build,
    factory: spectacular.factories.factory,
    create: spectacular.factories.create
  };

  function Environment(options) {
    this.options = options;
    this.shouldnt = __bind(this.shouldnt, this);
    this.should = __bind(this.should, this);
    this.fixture = __bind(this.fixture, this);
    this.spyOn = __bind(this.spyOn, this);
    this.whenPass = __bind(this.whenPass, this);
    this.dependsOn = __bind(this.dependsOn, this);
    this.withArguments = __bind(this.withArguments, this);
    this.withParameters = __bind(this.withParameters, this);
    this.xcontext = __bind(this.xcontext, this);
    this.context = __bind(this.context, this);
    this.xdescribe = __bind(this.xdescribe, this);
    this.describe = __bind(this.describe, this);
    this.given = __bind(this.given, this);
    this.subject = __bind(this.subject, this);
    this.itsReturn = __bind(this.itsReturn, this);
    this.itsInstance = __bind(this.itsInstance, this);
    this.its = __bind(this.its, this);
    this.after = __bind(this.after, this);
    this.before = __bind(this.before, this);
    this.xit = __bind(this.xit, this);
    this.specify = __bind(this.specify, this);
    this.the = __bind(this.the, this);
    this.it = __bind(this.it, this);
    this.success = __bind(this.success, this);
    this.skip = __bind(this.skip, this);
    this.pending = __bind(this.pending, this);
    this.fail = __bind(this.fail, this);
    this.notOutsideIt = __bind(this.notOutsideIt, this);
    this.notInsideIt = __bind(this.notInsideIt, this);
    this.load = __bind(this.load, this);
    this.run = __bind(this.run, this);
    this.rootExampleGroup = new spectacular.ExampleGroup;
    this.currentExampleGroup = this.rootExampleGroup;
    this.currentExample = null;
    this.runner = new spectacular.Runner(this.rootExampleGroup, this.options, this);
    this.registerFixtureHandler('json', this.handleJSONFixture);
  }

  Environment.prototype.run = function() {
    return this.runner.run();
  };

  Environment.prototype.load = function() {
    this.loadObjectExtensions();
    this.loadSpectacularMethods();
    this.loadSpectacularMatchers();
    return this.loadSpectacularEnvironment();
  };

  Environment.prototype.loadSpectacularEnvironment = function() {
    var env,
      _this = this;

    env = this;
    return this.exposedMethods.split(/\s+/g).forEach(function(k) {
      var fn;

      fn = function() {
        return env[k].apply(env, arguments);
      };
      fn._name = k;
      return spectacular.global[k] = fn;
    });
  };

  Environment.prototype.loadSpectacularMatchers = function() {
    var _ref, _results;

    _ref = spectacular.matchers;
    _results = [];
    for (k in _ref) {
      v = _ref[k];
      v._name = k;
      _results.push(spectacular.global[k] = v);
    }
    return _results;
  };

  Environment.prototype.loadSpectacularMethods = function() {
    var _ref, _results;

    _ref = this.exposedSpectacularMethods;
    _results = [];
    for (k in _ref) {
      v = _ref[k];
      v._name = k;
      _results.push(spectacular.global[k] = v);
    }
    return _results;
  };

  Environment.prototype.loadObjectExtensions = function() {
    var env;

    env = this;
    Object.defineProperty(Object.prototype, 'should', {
      writable: true,
      enumerable: false,
      value: function(matcher, neg) {
        if (neg == null) {
          neg = false;
        }
        env.notOutsideIt('should');
        if (matcher == null) {
          return;
        }
        return env.currentExample.result.addExpectation(new spectacular.Expectation(env.currentExample, this.valueOf(), matcher, neg, new Error));
      }
    });
    return Object.defineProperty(Object.prototype, 'shouldnt', {
      writable: true,
      enumerable: false,
      value: function(matcher) {
        env.notOutsideIt('should');
        return this.should(matcher, true);
      }
    });
  };

  Environment.prototype.clone = function() {
    var optionsCopy, _ref;

    optionsCopy = {};
    _ref = this.options;
    for (k in _ref) {
      v = _ref[k];
      optionsCopy[k] = v;
    }
    return new spectacular.Environment(optionsCopy);
  };

  Environment.prototype.notInsideIt = function(method) {
    if (this.currentExample != null) {
      throw new Error("" + method + " called inside a it block");
    }
  };

  Environment.prototype.notOutsideIt = function(method) {
    if (this.currentExample == null) {
      throw new Error("" + method + " called outside a it block");
    }
  };

  Environment.prototype.fail = function() {
    return this.currentExample.reject(new Error('Failed'));
  };

  Environment.prototype.pending = function() {
    return this.currentExample.pending();
  };

  Environment.prototype.skip = function() {
    return this.currentExample.skip();
  };

  Environment.prototype.success = function() {};

  Environment.prototype.it = function(msgOrBlock, block) {
    var _ref;

    this.notInsideIt('it');
    if (typeof msgOrBlock === 'function') {
      _ref = ['', msgOrBlock], msgOrBlock = _ref[0], block = _ref[1];
    }
    return this.currentExampleGroup.addChild(new spectacular.Example(block, msgOrBlock, this.currentExampleGroup));
  };

  Environment.prototype.the = function(msgOrBlock, block) {
    this.notInsideIt('the');
    return this.it(msgOrBlock, block);
  };

  Environment.prototype.specify = function(msgOrBlock, block) {
    this.notInsideIt('specify');
    return this.it(msgOrBlock, block);
  };

  Environment.prototype.xit = function(msgOrBlock, block) {
    this.notInsideIt('xit');
    if (typeof msgOrBlock === 'string') {
      return this.it(msgOrBlock, function() {
        return pending();
      });
    } else {
      return this.it(function() {
        return pending();
      });
    }
  };

  Environment.prototype.before = function(block) {
    this.notInsideIt('before');
    return this.currentExampleGroup.ownBeforeHooks.push(block);
  };

  Environment.prototype.after = function(block) {
    this.notInsideIt('after');
    return this.currentExampleGroup.ownAfterHooks.push(block);
  };

  Environment.prototype.its = function(property, block) {
    var parentSubjectBlock,
      _this = this;

    this.notInsideIt('its');
    parentSubjectBlock = this.currentExampleGroup.subjectBlock;
    return this.context("" + property + " property", function() {
      _this.subject(property, function() {
        return typeof parentSubjectBlock === "function" ? parentSubjectBlock()[property] : void 0;
      });
      return _this.it(block);
    });
  };

  Environment.prototype.itsInstance = function(block) {
    var parentSubjectBlock,
      _this = this;

    this.notInsideIt('itsInstance');
    parentSubjectBlock = this.currentExampleGroup.subjectBlock;
    return this.context('instance', function() {
      _this.subject('instance', function() {
        return build(typeof parentSubjectBlock === "function" ? parentSubjectBlock() : void 0, this.parameters || []);
      });
      return _this.it(block);
    });
  };

  Environment.prototype.itsReturn = function(block) {
    var parentSubjectBlock,
      _this = this;

    this.notInsideIt('itsReturn');
    parentSubjectBlock = this.currentExampleGroup.subjectBlock;
    return this.context('returned value', function() {
      _this.subject('returnedValue', function() {
        return typeof parentSubjectBlock === "function" ? parentSubjectBlock().apply(this, this.parameters || []) : void 0;
      });
      return _this.it(block);
    });
  };

  Environment.prototype.subject = function(name, block) {
    var _ref;

    this.notInsideIt('subject');
    if (typeof name === 'function') {
      _ref = [block, name], name = _ref[0], block = _ref[1];
    }
    this.currentExampleGroup.ownSubjectBlock = block;
    if (name != null) {
      return this.given(name, block);
    }
  };

  Environment.prototype.given = function(name, block) {
    this.notInsideIt('given');
    return this.before(function() {
      var _this = this;

      return Object.defineProperty(this, name, {
        configurable: true,
        enumerable: true,
        get: function() {
          var _name;

          return _this[_name = "__" + name] || (_this[_name] = block.call(_this));
        }
      });
    });
  };

  Environment.prototype.describe = function(subject, options, block) {
    var error, oldGroup, _ref;

    if (typeof options === 'function') {
      _ref = [block, options], options = _ref[0], block = _ref[1];
    }
    this.notInsideIt('describe');
    oldGroup = this.currentExampleGroup;
    this.currentExampleGroup = new spectacular.ExampleGroup(block, subject, oldGroup, options);
    oldGroup.addChild(this.currentExampleGroup);
    try {
      return this.currentExampleGroup.executeBlock();
    } catch (_error) {
      error = _error;
    } finally {
      this.currentExampleGroup = oldGroup;
      if (error != null) {
        throw error;
      }
    }
  };

  Environment.prototype.xdescribe = function(subject, options, block) {
    var _ref;

    this.notInsideIt('xdescribe');
    if (typeof options === 'function') {
      _ref = [block, options], options = _ref[0], block = _ref[1];
    }
    return describe(subject, function() {
      return it(function() {
        return pending();
      });
    });
  };

  Environment.prototype.context = function(subject, options, block) {
    this.notInsideIt('context');
    return this.describe(subject, options, block);
  };

  Environment.prototype.xcontext = function(subject, options, block) {
    this.notInsideIt('xcontext');
    return this.xdescribe(subject, options, block);
  };

  Environment.prototype.withParameters = function() {
    var args;

    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    this.notInsideIt('withParameters');
    return this.given('parameters', function() {
      return args;
    });
  };

  Environment.prototype.withArguments = function() {
    this.notInsideIt('withArguments');
    return this.withParameters.apply(this, arguments);
  };

  Environment.prototype.dependsOn = function(spec) {
    this.notInsideIt('dependsOn');
    return this.currentExampleGroup.ownDependencies.push(spec);
  };

  Environment.prototype.whenPass = function(block) {
    var previousContext,
      _this = this;

    this.notInsideIt('whenPass');
    previousContext = this.currentExampleGroup;
    return this.context('', function() {
      _this.currentExampleGroup.ownCascading = previousContext;
      return block();
    });
  };

  Environment.prototype.spyOn = function(obj, method) {
    var context, oldMethod, spy;

    this.notOutsideIt('spyOn');
    oldMethod = obj[method];
    context = this.currentExample.context;
    spy = function() {
      var args;

      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      spy.argsForCall.push(args);
      if (spy.mock != null) {
        return spy.mock.apply(obj, args);
      } else {
        return oldMethod.apply(obj, args);
      }
    };
    spy.spied = oldMethod;
    spy.argsForCall = [];
    spy.andCallFake = function(mock) {
      this.mock = mock;
      return this;
    };
    spy.andReturns = function(value) {
      return spy.andCallFake(function() {
        return value;
      });
    };
    spy.andCallThrough = function(block) {
      this.mock = function() {
        return block.call(context, oldMethod.apply(this, arguments));
      };
      return this;
    };
    this.currentExample.ownAfterHooks.push(function() {
      return obj[method] = oldMethod;
    });
    obj[method] = spy;
    return spy;
  };

  Environment.prototype.fixture = function(file, options) {
    var env, envOptions, ext, name;

    if (options == null) {
      options = {};
    }
    this.notInsideIt('fixture');
    name = options.as || 'fixture';
    env = this;
    envOptions = this.options;
    ext = file.split('.').slice(-1)[0];
    return this.before(function(async) {
      var p,
        _this = this;

      p = "" + envOptions.fixturesRoot + "/" + file;
      return envOptions.loadFile(p).then(function(fileContent) {
        return env.handleFixture(ext, fileContent).then(function(result) {
          _this[name] = result;
          return async.resolve();
        });
      }).fail(function(reason) {
        return async.reject(reason);
      });
    });
  };

  Environment.prototype.registerFixtureHandler = function(ext, proc) {
    this.fixtureHandlers || (this.fixtureHandlers = {});
    return this.fixtureHandlers[ext] = proc;
  };

  Environment.prototype.handleFixture = function(ext, content) {
    if (ext in this.fixtureHandlers) {
      return this.fixtureHandlers[ext](content);
    } else {
      return spectacular.Promise.unit(content);
    }
  };

  Environment.prototype.handleJSONFixture = function(content) {
    return spectacular.Promise.unit(JSON.parse(content));
  };

  Environment.prototype.should = function(matcher, neg) {
    if (neg == null) {
      neg = false;
    }
    this.notOutsideIt('should');
    if (matcher == null) {
      return;
    }
    return this.currentExample.result.addExpectation(new spectacular.Expectation(this.currentExample, this.currentExample.subject, matcher, neg, new Error));
  };

  Environment.prototype.shouldnt = function(matcher) {
    return this.should(matcher, true);
  };

  Environment.prototype.toString = function() {
    return '[spectacular Environment]';
  };

  return Environment;

})();

spectacular.matchers || (spectacular.matchers = {});

spectacular.matchers.exist = {
  assert: function(actual, notText) {
    this.description = "should" + notText + " exist";
    this.message = "Expected " + actual + notText + " to exist";
    return actual != null;
  }
};

spectacular.matchers.have = function(count, label) {
  return {
    assert: function(actual, notText) {
      var andOrBut;

      this.description = "should" + notText + " have " + count + " " + label;
      switch (typeof actual) {
        case 'string':
          label || (label = 'chars');
          andOrBut = notText.length === 0 ? actual.length === count : actual.length !== count;
          this.description = "should" + notText + " have " + count + " " + label;
          this.message = "Expected string " + (utils.inspect(actual)) + notText + " to have " + count + " " + label + " " + (utils.andOrBut(andOrBut)) + " was " + actual.length;
          return actual.length === count;
        case 'object':
          if (utils.isArray(actual)) {
            andOrBut = notText.length === 0 ? actual.length === count : actual.length !== count;
            label || (label = 'items');
            this.description = "should" + notText + " have " + count + " " + label;
            this.message = "Expected array " + (utils.inspect(actual)) + notText + " to have " + count + " " + label + " " + (utils.andOrBut(andOrBut)) + " was " + actual.length;
            return actual.length === count;
          } else {
            if (label == null) {
              throw new Error("Undefined label in have matcher");
            }
            this.description = "should" + notText + " have " + count + " " + label;
            if (actual[label]) {
              if (utils.isArray(actual[label])) {
                andOrBut = notText.length === 0 ? actual[label].length === count : actual[label].length !== count;
                this.message = "Expected object " + (utils.inspect(actual)) + notText + " to have " + count + " " + label + " " + (utils.andOrBut(andOrBut)) + " was " + actual[label].length;
                return actual[label].length === count;
              } else {
                andOrBut = notText.length !== 0;
                this.message = "Expected object " + (utils.inspect(actual)) + notText + " to have " + count + " " + label + " " + (utils.andOrBut(andOrBut)) + " " + actual[label] + " wasn't an array";
                return false;
              }
            } else {
              andOrBut = notText.length !== 0;
              this.message = "Expected object " + (utils.inspect(actual)) + notText + " to have " + count + " " + label + " " + (utils.andOrBut(andOrBut)) + " it didn't have a property named " + label;
              return false;
            }
          }
          break;
        default:
          andOrBut = notText.length !== 0;
          this.message = "Expected " + (utils.inspect(actual)) + notText + " to have " + count + " " + label + " " + (utils.andOrBut(andOrBut)) + " it don't belong to a type that can be handled";
          return false;
      }
    }
  };
};

spectacular.matchers.be = function(value) {
  return {
    assert: function(actual, notText) {
      var r, result, state;

      this.description = "should" + notText + " be " + value;
      switch (typeof value) {
        case 'string':
          state = utils.findStateMethodOrProperty(actual, value);
          if (state != null) {
            if (typeof actual[state] === 'function') {
              result = actual[state]();
              r = notText.length === 0 ? result : !result;
              this.message = "Expected " + actual + "." + state + "()" + notText + " to be true " + (utils.andOrBut(r)) + " was " + (actual[state]());
            } else {
              result = actual[state];
              r = notText.length === 0 ? result : !result;
              this.message = "Expected " + actual + "." + state + notText + " to be true " + (utils.andOrBut(r)) + " was " + actual[state];
            }
          } else {
            this.message = "Expected " + actual + " to be " + value + " " + (utils.andOrBut(notText.length !== 0)) + " the state can't be found";
            result = false;
          }
          return result;
        case 'number':
        case 'boolean':
          this.message = "Expected " + actual + notText + " to be " + value;
          return actual.valueOf() === value;
        default:
          this.description = "should" + notText + " be " + (utils.squeeze(utils.inspect(value)));
          this.message = "Expected " + (utils.inspect(actual)) + notText + " to be " + (utils.inspect(value));
          return actual === value;
      }
    }
  };
};

spectacular.matchers.equal = function(value) {
  return {
    assert: function(actual, notText) {
      this.description = "should" + notText + " be equal to " + (utils.squeeze(utils.inspect(value)));
      this.message = "Expected " + (utils.inspect(actual)) + notText + " to be equal to " + (utils.inspect(value));
      return utils.compare(actual, value, this);
    }
  };
};

spectacular.matchers.match = function(re) {
  return {
    assert: function(actual, notText) {
      this.description = "should" + notText + " match " + re;
      this.message = "Expected '" + actual + "'" + notText + " to match " + re;
      return re.test(actual);
    }
  };
};

spectacular.matchers.throwAnError = function(message) {
  return {
    assert: function(actual, notText) {
      var error, msg, r, result;

      msg = message != null ? " with message " + message : '';
      if (this["arguments"] != null) {
        msg += " with arguments " + (utils.inspect(this["arguments"]));
      }
      this.description = "should" + notText + " throw an error" + msg;
      try {
        if (this["arguments"] != null) {
          actual.apply(this.context, this["arguments"]);
        } else {
          actual.call(this.context);
        }
      } catch (_error) {
        error = _error;
      }
      result = message != null ? (error != null) && message.test(error.message) : error != null;
      r = notText.length === 0 ? result : !result;
      this.message = "Expected" + notText + " to throw an error" + msg + " " + (utils.andOrBut(r)) + " was " + error;
      return result;
    },
    "with": function() {
      var arguments, _arguments;

      _arguments = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      this["arguments"] = _arguments;
      return this;
    },
    inContext: function(context) {
      this.context = context;
      return this;
    }
  };
};

spectacular.matchers.haveBeenCalled = {
  assert: function(actual, notText) {
    var _this = this;

    if (typeof (actual != null ? actual.spied : void 0) === 'function') {
      if (this["arguments"] != null) {
        this.description = "should have been called with " + (utils.inspect(this["arguments"]));
        this.message = "Expected " + actual.spied + notText + " to have been called with " + (utils.inspect(this["arguments"])) + " but was called with " + actual.argsForCall;
        return actual.argsForCall.length > 0 && actual.argsForCall.some(function(a) {
          return equal(a).assert(_this["arguments"], '');
        });
      } else {
        this.description = "should have been called";
        this.message = "Expected " + actual.spied + notText + " to have been called";
        return actual.argsForCall.length > 0;
      }
    } else {
      this.description = "should be a spy that have been called";
      this.message = "Expected a spy but it was " + actual;
      return false;
    }
  },
  "with": function() {
    var arguments, _arguments;

    _arguments = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    this["arguments"] = _arguments;
    return this;
  }
};

spectacular.StackReporter = (function() {
  function StackReporter(error, options) {
    this.error = error;
    this.options = options;
  }

  StackReporter.prototype.format = function() {
    var promise, res, stack,
      _this = this;

    promise = new spectacular.Promise;
    if (this.error.stack != null) {
      stack = this.error.stack.split('\n').filter(function(line) {
        return /(at|@)/g.test(line);
      });
      res = '\n';
      if (this.options.showSource) {
        this.formatErrorInFile(stack[0]).then(function(msg) {
          res += msg + _this.formatStack(stack);
          if (!_this.options.noColors) {
            res = res.grey;
          }
          return promise.resolve(res);
        });
      } else {
        res += this.formatStack(stack);
        if (!this.options.noColors) {
          res = res.grey;
        }
        promise.resolve(res);
      }
    } else {
      promise.resolve(res);
    }
    return promise;
  };

  StackReporter.prototype.formatStack = function(stack) {
    var s;

    if (this.options.longTrace) {
      return "\n\n" + (stack.join('\n')) + "\n";
    } else {
      s = "\n" + (stack.slice(0, 6).join('\n'));
      if (/@/.test(s)) {
        s = utils.indent(s);
      }
      if (stack.length > 6) {
        s += "\n    ...\n\n    use --long-trace option to view the " + (stack.length - 6) + " remaining lines";
      }
      return s += "\n\n";
    }
  };

  StackReporter.prototype.formatErrorInFile = function(line) {
    var c, column, e, file, h, match, p, promise, re, _ref;

    promise = new spectacular.Promise;
    re = /(at.*\(|@)((http:\/\/)?.*\.(js|coffee)):(\d+)(:(\d+))*/;
    if (!re.test(line)) {
      promise.resolve('');
      return promise;
    }
    _ref = re.exec(line), match = _ref[0], p = _ref[1], file = _ref[2], h = _ref[3], e = _ref[4], line = _ref[5], c = _ref[6], column = _ref[7];
    if ((column == null) && (this.error.columnNumber != null)) {
      column = this.error.columnNumber + 1;
    }
    this.getLines(file, parseInt(line), parseInt(column)).then(function(lines) {
      return promise.resolve("\n" + lines + "\n");
    });
    return promise;
  };

  StackReporter.prototype.getLines = function(file, line, column) {
    var promise,
      _this = this;

    promise = new spectacular.Promise;
    this.options.loadFile(file).then(function(fileContent) {
      var endLine, lines, startLine;

      fileContent = fileContent.split('\n').map(function(l, i) {
        return "    " + (utils.padRight(i + 1)) + " | " + l;
      });
      _this.insertColumnLine(fileContent, line, column);
      startLine = Math.max(1, line - 3) - 1;
      endLine = Math.min(fileContent.length, line + 2) - 1;
      lines = fileContent.slice(startLine, +endLine + 1 || 9e9).join('\n');
      return promise.resolve(lines);
    });
    return promise;
  };

  StackReporter.prototype.insertColumnLine = function(content, line, column) {
    if (line === content.length) {
      return content.push(line);
    } else {
      return content.splice(line, 0, "         | " + (utils.padRight('^', column)));
    }
  };

  return StackReporter;

})();

spectacular.ConsoleReporter = (function() {
  ConsoleReporter.include(spectacular.EventDispatcher);

  function ConsoleReporter(options) {
    this.options = options;
    this.printExampleResult = __bind(this.printExampleResult, this);
    this.formatResult = __bind(this.formatResult, this);
    this.onEnd = __bind(this.onEnd, this);
    this.onResult = __bind(this.onResult, this);
    this.errorsCounter = 1;
    this.failuresCounter = 1;
    this.errors = [];
    this.failures = [];
    this.skipped = [];
    this.pending = [];
    this.results = [];
    this.examples = [];
  }

  ConsoleReporter.prototype.onResult = function(event) {
    var example;

    example = event.target;
    this.printExampleResult(example);
    this.results.push(example.result);
    this.examples.push(example);
    switch (example.result.state) {
      case 'pending':
        return this.pending.push(example);
      case 'skipped':
        return this.skipped.push(example);
      case 'errored':
        return this.errors.push(example);
      case 'failure':
        return this.failures.push(example);
    }
  };

  ConsoleReporter.prototype.onEnd = function(event) {
    var runner,
      _this = this;

    runner = event.target;
    return this.buildResults(runner.loadStartedAt, runner.loadEndedAt, runner.specsStartedAt, runner.specsEndedAt).then(function(report) {
      return _this.dispatch(new spectacular.Event('report', report));
    });
  };

  ConsoleReporter.prototype.buildResults = function(lstart, lend, sstart, send) {
    var promise, res, result,
      _this = this;

    promise = new spectacular.Promise;
    res = '\n\n';
    spectacular.Promise.all((function() {
      var _i, _len, _ref, _results;

      _ref = this.results;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        result = _ref[_i];
        _results.push(this.formatResult(result));
      }
      return _results;
    }).call(this)).then(function(results) {
      res += results.filter(function(s) {
        return (s != null) && s.length > 0;
      }).join('\n');
      res += _this.formatResume();
      if (_this.options.profile) {
        res += _this.formatProfile(sstart, send);
      }
      res += _this.formatTimers(lstart, lend, sstart, send);
      res += _this.formatCounters();
      res += '\n\n';
      return promise.resolve(res);
    });
    return promise;
  };

  ConsoleReporter.prototype.formatResult = function(result) {
    var expectation, promise, _i, _len, _ref;

    promise = new spectacular.Promise;
    switch (result.state) {
      case 'errored':
        this.formatExampleError(result.example).then(function(msg) {
          return promise.resolve(msg);
        });
        break;
      case 'failure':
        if (result.expectations.length > 0) {
          _ref = result.expectations;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            expectation = _ref[_i];
            if (!expectation.success) {
              this.formatExpectationFailure(expectation).then(function(msg) {
                return promise.resolve(msg);
              });
            }
          }
        } else {
          this.formatExampleFailure(result.example).then(function(msg) {
            return promise.resolve(msg);
          });
        }
        break;
      default:
        promise.resolve('');
    }
    return promise;
  };

  ConsoleReporter.prototype.printExampleResult = function(example) {
    var res;

    res = this.formatExampleResult(example);
    if (res != null) {
      return this.dispatch(new spectacular.Event('message', res));
    }
  };

  ConsoleReporter.prototype.formatExampleResult = function(example) {
    if (this.options.noColors) {
      switch (example.result.state) {
        case 'pending':
          return '*';
        case 'skipped':
          return 'x';
        case 'failure':
          return 'F';
        case 'errored':
          return 'E';
        case 'success':
          return '.';
      }
    } else {
      switch (example.result.state) {
        case 'pending':
          return '*'.yellow;
        case 'skipped':
          return 'x'.magenta;
        case 'failure':
          return 'F'.red;
        case 'errored':
          return 'E'.yellow;
        case 'success':
          return '.'.green;
      }
    }
  };

  ConsoleReporter.prototype.formatStack = function(e) {
    return new spectacular.StackReporter(e, this.options).format();
  };

  ConsoleReporter.prototype.formatExampleFailure = function(example) {
    var promise, res;

    promise = new spectacular.Promise;
    res = this.failureBadge(example.description);
    this.formatError(example.reason).then(function(msg) {
      res += msg + '\n';
      return promise.resolve(res);
    });
    return promise;
  };

  ConsoleReporter.prototype.formatExpectationFailure = function(expectation) {
    var promise, res;

    promise = new spectacular.Promise;
    res = this.failureBadge(expectation.fullDescription);
    res += '\n';
    res += this.formatMessage(expectation.message);
    if (this.options.trace) {
      this.formatStack(expectation.trace).then(function(msg) {
        if (msg != null) {
          res += msg;
        }
        return promise.resolve(res + '\n');
      });
    } else {
      promise.resolve(res);
    }
    return promise;
  };

  ConsoleReporter.prototype.formatExampleError = function(example) {
    var promise, res;

    promise = new spectacular.Promise;
    res = this.errorBadge(example.description);
    this.formatError(example.reason).then(function(msg) {
      return promise.resolve(res + msg);
    });
    return promise;
  };

  ConsoleReporter.prototype.formatError = function(error) {
    var promise, res;

    promise = new spectacular.Promise;
    res = this.formatMessage(error.message);
    if (this.options.trace) {
      this.formatStack(error).then(function(msg) {
        return promise.resolve(res + msg);
      });
    } else {
      promise.resolve(res);
    }
    return promise;
  };

  ConsoleReporter.prototype.failureBadge = function(message) {
    var badge;

    badge = ' FAIL ';
    if (this.options.noColors) {
      return "" + badge + " - " + (this.failuresCounter++) + " - " + message + "\n";
    } else {
      return ("" + badge.inverse.bold + " " + (this.failuresCounter++) + " " + ' '.inverse + " " + message + "\n").red;
    }
  };

  ConsoleReporter.prototype.errorBadge = function(message) {
    var badge;

    badge = ' ERROR ';
    if (this.options.noColors) {
      return "" + badge + " - " + (this.errorsCounter++) + " - " + message + "\n";
    } else {
      return ("" + badge.inverse.bold + " " + (this.errorsCounter++) + " " + ' '.inverse + " " + message + "\n").yellow;
    }
  };

  ConsoleReporter.prototype.formatMessage = function(message) {
    return "\n" + (utils.indent(message || ''));
  };

  ConsoleReporter.prototype.formatResume = function() {
    var res;

    res = '';
    if (this.errors.length > 0) {
      res += this.mapDescription('Errors:', this.errors, 'yellow');
    }
    if (this.failures.length > 0) {
      res += this.mapDescription('Failures:', this.failures, 'red');
    }
    if (this.skipped.length > 0) {
      res += this.mapDescription('Skipped:', this.skipped, 'magenta');
    }
    if (this.pending.length > 0) {
      res += this.mapDescription('Pending:', this.pending, 'yellow');
    }
    return res;
  };

  ConsoleReporter.prototype.formatProfile = function(specsStartedAt, specsEndedAt) {
    var duration, example, rate, res, sortedExamples, topSlowest, totalDuration, _i, _len;

    sortedExamples = this.examples.sort(function(a, b) {
      return b.duration - a.duration;
    }).slice(0, 10);
    totalDuration = specsEndedAt.getTime() - specsStartedAt.getTime();
    topSlowest = sortedExamples.reduce((function(a, b) {
      return a + b.duration;
    }), 0);
    rate = Math.floor(topSlowest / totalDuration * 10000) / 100;
    res = "Top 10 slowest examples (" + (topSlowest / 1000) + " seconds, " + rate + "% of total time)\n\n";
    for (_i = 0, _len = sortedExamples.length; _i < _len; _i++) {
      example = sortedExamples[_i];
      duration = "" + (Math.floor(example.duration) / 1000) + " seconds";
      res += "    " + (this.options.noColors ? duration : duration.red) + " " + example.fullDescription + "\n";
    }
    return "" + res + "\n";
  };

  ConsoleReporter.prototype.mapDescription = function(desc, array, color) {
    var res;

    res = "    " + desc + "\n\n";
    res += array.map(function(e, i) {
      return "      " + (i + 1) + ". " + e.description;
    }).join('\n');
    if (!this.options.noColors) {
      res = res[color];
    }
    return "" + res + "\n\n";
  };

  ConsoleReporter.prototype.formatTimers = function(loadStartedAt, loadEndedAt, specsStartedAt, specsEndedAt) {
    var loadDuration, res, specsDuration;

    if ((loadStartedAt != null) && (loadEndedAt != null)) {
      loadDuration = this.formatDuration(loadStartedAt, loadEndedAt);
    }
    specsDuration = this.formatDuration(specsStartedAt, specsEndedAt);
    res = '';
    if (loadDuration != null) {
      res += "Specs loaded in " + loadDuration + "\n";
    }
    return res += "Finished in " + specsDuration + "\n\n";
  };

  ConsoleReporter.prototype.formatCounters = function() {
    var assertions, errored, failures, pending, skipped, success;

    failures = this.failures.length;
    errored = this.errors.length;
    skipped = this.skipped.length;
    pending = this.pending.length;
    success = this.examples.length - failures - errored - pending - skipped;
    assertions = this.results.reduce((function(a, b) {
      return a + b.expectations.length;
    }), 0);
    return this.formatResults(success, failures, errored, skipped, pending, assertions);
  };

  ConsoleReporter.prototype.formatResults = function(s, f, e, sk, p, a) {
    var he, toggle;

    toggle = utils.toggle;
    he = f + e;
    return utils.squeeze("" + (this.formatCount(s, 'success', 'success', toggle(he, 'green'))) + ",    " + (this.formatCount(a, 'assertion', 'assertions', toggle(he, 'green'))) + ",    " + (this.formatCount(f, 'failure', 'failures', toggle(he, 'green', 'red'))) + ",    " + (this.formatCount(e, 'error', 'errors', toggle(e, 'green', 'yellow'))) + ",    " + (this.formatCount(sk, 'skipped', 'skipped', toggle(sk, 'green', 'magenta'))) + ",    " + (this.formatCount(p, 'pending', 'pending', toggle(p, 'green', 'yellow'))));
  };

  ConsoleReporter.prototype.formatDuration = function(start, end) {
    var duration;

    duration = (end.getTime() - start.getTime()) / 1000;
    duration = "" + (Math.max(0, duration)) + "s";
    if (!this.options.noColors) {
      duration = duration.yellow;
    }
    return duration;
  };

  ConsoleReporter.prototype.formatCount = function(value, singular, plural, color) {
    var s;

    s = "" + value + " " + (value === 0 ? plural : value === 1 ? singular : plural);
    if ((color != null) && !this.options.noColors) {
      s = s[color];
    }
    return s;
  };

  return ConsoleReporter;

})();
