// Generated by CoffeeScript 1.6.2
var exports, isCommonJS;

isCommonJS = typeof window === "undefined";

exports = exports || window;

exports.squeeze = function(s) {
  return s.replace(/\s+/g, ' ');
};

exports.indent = function(string, ind) {
  var i, s, _i, _ref;

  if (ind == null) {
    ind = 4;
  }
  s = '';
  for (i = _i = 0, _ref = ind - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
    s = "" + s + " ";
  }
  return "" + s + (string.replace(/\n/g, "\n" + s));
};

exports.padRight = function(string, pad) {
  if (pad == null) {
    pad = 4;
  }
  string = string.toString();
  while (string.length < pad) {
    string = " " + string;
  }
  return string;
};

exports.toggle = function(value, c1, c2) {
  if (value) {
    return c2;
  } else {
    return c1;
  }
};
